export var namesList = [
    "Dave",
    "Lukas",
    "Yasmine",
    "Johannes",
    "JaCob",
    "Doris",
    "Paolo",
    "Angela Merkel",
    "Die Dohnal",
    "Hugo",
    "Mortimer",
    "Timothy",
    "Sandra",
    "Maria",
    "Magdalena",
    "Ingrid",
    "Nelly",
    "JaKob",
    "Sophie",
    "Gerald",
    "Frau Huber",
    "Babsi",
    "Roland",
    "Klaus",
    "Norbert",
    "Scooter",
    "Orlando",
    "Virginia Woolf",
    "Queen Elisabeth",
    "Nora",
    "Tom",
    "Bimbolino",
    "Ronaldinho",
    "Flupsi",
    "Betti",
    "Jesus",
    "John Schnee",
    "Aragorn",
    "Gimli",
    "Prince Harry",
    "Maria Magdalena",
    "Scotty",
    "Bulli",
    "Betti",
    "Rudi",
    "Herwig",
    "Verena",
    "Wolfgang",
    "Stefan",
    "Stephanie",
    "Alex",
    "Ferdl",
    "Franzl",
    "Sissi",
    "Göthe",
    "Pam",
    "Sigi",
    "Beate",
    "Klenk",
    "Mimi",
    "Rüdiger",
    "Funny",
    "Aslan",
    "Ludwig",
    "Wilhelm",
    "Emmerich",
    "Lutz",
    "Simon",
    "Simone",
    "Ilse",
    "Rachel",
    "Ross",
    "She-ra",
    "Adora",
    "Cornelia",
    "Francis",
    "Malcolm",
    "Sugar Pie",
    "Nadine",
    "Ridi",
    "Hulio",
    "Udo",
    "Jürgen",
    "Helene Fischer"

];